service: fbrealtimedb
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser
  region: ap-southeast-1

functions:
  createUser:
    handler: createUser.handler
    events:
      - http:
          path: create-user
          method: POST
          cors: true
  requestOTP:
    handler: requestOTP.handler
    events:
      - http:
          path: request-otp
          method: POST
          cors: true
  verifyOTP:
    handler: verifyOTP.handler
    events:
      - http:
          path: verify-otp
          method: POST
          cors: true
